### PR TITLE
Games: Ignore when guess has a typo in some games

### PR DESCRIPTION
**Pull request by Dirain1700**
Approved by Game Corner Staff.

### CODE REVIEW

**Comment by Dirain1700** [comment]
I want to add function to test filterGuess(), but I have no idea how to make typo on purpose. Do you have an idea?

**Comment by Dirain1700** [comment]
Now ignoring typos in: Chimecho's Stat School Natu's Nature Min-Max, Xatu's Nature Clusters, so I convert this to draft (Approved by WarriorGallade)

**Comment by Dirain1700** [comment]
fixing it now

**Comment by sirDonovan** [comment]
No worries, it's not related to your changes

**Comment by sirDonovan** [comment]
Sorry I only saw the unrelated errors from the `master` branch before. You might need to have the new test in each individual game it applies to instead of `QuestionAndAnswer`

**Comment by sirDonovan** [comment]
Any game that extends the `QuestionAndAnswer` class will also inherit its unit tests

**Comment by Dirain1700** [comment]
ik, so i put the guard, but toss up threw the guard

**Comment by Dirain1700** [comment]
I did not realized Hangman and some games have a filterGuess, I fix this right now

**Review by sirDonovan — APPROVED** [review]

**Comment by sirDonovan** [comment]
Thanks!

**Pull request merged**
